// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbHEzC6X_QsxXJVHui4KUN_KvJauAHEB4',
    appId: '1:465150723749:web:b1f6ece7bb0ccff065ef4c',
    messagingSenderId: '465150723749',
    projectId: 'kyysh-e8b88',
    authDomain: 'kyysh-e8b88.firebaseapp.com',
    storageBucket: 'kyysh-e8b88.appspot.com',
    measurementId: 'G-NBN9RTHVGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo0bOLRekwWgwCOYnJSQ1MMeF8J5quXx4',
    appId: '1:465150723749:android:32ed158ad63256fe65ef4c',
    messagingSenderId: '465150723749',
    projectId: 'kyysh-e8b88',
    storageBucket: 'kyysh-e8b88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNeTETm5u2OURIPT-IOmRS8kHimXWbtDQ',
    appId: '1:465150723749:ios:d075129449fdbb8665ef4c',
    messagingSenderId: '465150723749',
    projectId: 'kyysh-e8b88',
    storageBucket: 'kyysh-e8b88.appspot.com',
    iosBundleId: 'com.example.kyysh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNeTETm5u2OURIPT-IOmRS8kHimXWbtDQ',
    appId: '1:465150723749:ios:d075129449fdbb8665ef4c',
    messagingSenderId: '465150723749',
    projectId: 'kyysh-e8b88',
    storageBucket: 'kyysh-e8b88.appspot.com',
    iosBundleId: 'com.example.kyysh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbHEzC6X_QsxXJVHui4KUN_KvJauAHEB4',
    appId: '1:465150723749:web:19dcd880e859b00765ef4c',
    messagingSenderId: '465150723749',
    projectId: 'kyysh-e8b88',
    authDomain: 'kyysh-e8b88.firebaseapp.com',
    storageBucket: 'kyysh-e8b88.appspot.com',
    measurementId: 'G-8B7VN8V0N8',
  );
}
